const UPSTREAM = "https://football-predict.pages.dev/api/daily-jingcai";
const HEADERS = {"content-type":"application/json; charset=utf-8","cache-control":"public, max-age=120, s-maxage=120","access-control-allow-origin":"*"};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:HEADERS});
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function normalize(a){const s=a.reduce((x,y)=>x+y,0);return s>0?a.map(x=>x/s):null}
function argmax(a){return a.indexOf(Math.max(...a))}
function oldProb(m){return normalize([n(m.homeWinProb??m.spf?.homeWinProb),n(m.drawProb??m.spf?.drawProb),n(m.awayWinProb??m.spf?.awayWinProb)])}
function marketProb(m){const a=[n(m.sp_win),n(m.sp_draw),n(m.sp_lose)];return a.every(x=>x>1)?normalize(a.map(x=>1/x)):null}
function eloProb(m){const eh=n(m.home_elo??m.homeElo??m.elo?.home,NaN),ea=n(m.away_elo??m.awayElo??m.elo?.away,NaN);if(!Number.isFinite(eh)||!Number.isFinite(ea))return null;const raw=1/(1+Math.pow(10,-((eh+65)-ea)/400)),draw=clamp(.30-Math.abs(raw-.5)*.22,.17,.30);return normalize([raw*(1-draw),draw,(1-raw)*(1-draw)])}
function factorial(k){let r=1;for(let i=2;i<=k;i++)r*=i;return r}
function pois(k,l){return Math.exp(-l)*Math.pow(l,k)/factorial(k)}
function matrix(lh,la,dc=false){if(!(lh>0&&la>0))return null;let h=0,d=0,a=0,total=0,scores=[];for(let i=0;i<=8;i++)for(let j=0;j<=8;j++){let p=pois(i,lh)*pois(j,la);if(dc){const rho=-.08;if(i===0&&j===0)p*=1-lh*la*rho;else if(i===0&&j===1)p*=1+lh*rho;else if(i===1&&j===0)p*=1+la*rho;else if(i===1&&j===1)p*=1-rho}p=Math.max(0,p);total+=p;if(i>j)h+=p;else if(i===j)d+=p;else a+=p;scores.push({score:`${i}:${j}`,prob:p})}scores.sort((x,y)=>y.prob-x.prob);return{probabilities:normalize([h,d,a]),scores:scores.slice(0,8).map(x=>({score:x.score,prob:x.prob/total*100}))}}
function sampleCount(m){for(const v of [m.sampleCount,m.historySample,m.history_samples,m.dataQuality?.sampleCount,m.dataQuality?.historySample,m.dataQuality?.samples,m.stats?.sampleCount])if(Number.isFinite(Number(v)))return Number(v);return 0}
function buildFusion(m){const legacy=oldProb(m),market=marketProb(m),elo=eloProb(m),lh=n(m.score?.homeLambda??m.homeLambda,NaN),la=n(m.score?.awayLambda??m.awayLambda,NaN),poisson=matrix(lh,la,false),dc=matrix(lh,la,true),models=[];if(elo)models.push({key:'elo',name:'Elo',weight:.20,probabilities:elo,source:'upstream-elo'});if(poisson)models.push({key:'poisson',name:'GX/Poisson',weight:.25,probabilities:poisson.probabilities,source:'upstream-lambda'});if(dc)models.push({key:'dixonColes',name:'Dixon-Coles',weight:.15,probabilities:dc.probabilities,source:'upstream-lambda-rho--0.08'});if(legacy)models.push({key:'legacy',name:'旧接口模型',weight:.15,probabilities:legacy,source:'daily-jingcai'});if(market)models.push({key:'market',name:'体彩SP去水',weight:.25,probabilities:market,source:'official-sp'});const sum=models.reduce((s,x)=>s+x.weight,0),fused=[0,0,0];for(const x of models)for(let i=0;i<3;i++)fused[i]+=x.probabilities[i]*x.weight/sum;const probabilities=normalize(fused)||[1/3,1/3,1/3],top=argmax(probabilities),consistency=models.length?models.filter(x=>argmax(x.probabilities)===top).length/models.length*100:0;return{version:'V16-P11',models:models.map(x=>({...x,probabilities:x.probabilities.map(v=>v*100),direction:['主胜','平局','客胜'][argmax(x.probabilities)]})),probabilities:probabilities.map(v=>v*100),modelCount:models.length,consistency:Number(consistency.toFixed(1)),weightsNormalized:true,scoreSource:dc?'dixon-coles':poisson?'poisson':'upstream',scores:dc?.scores||poisson?.scores||m.score?.topScores||[]}}
function grade(m,f){const p=f.probabilities,ord=[...p].sort((a,b)=>b-a),lead=ord[0]-ord[1],samples=sampleCount(m),reliability=n(m.dataQuality?.reliability??m.reliability),official=!!marketProb(m),quality=Math.min(100,samples*4+(official?25:0)+f.modelCount*8);let tier='C',reason='未达到B级门槛';if(official&&samples>=6&&f.modelCount>=4&&f.consistency>=70&&quality>=60&&lead>=10&&reliability>=45){tier='A';reason='样本、有效模型、一致性、官方SP与方向优势均达到A级'}else if(official&&samples>=3&&f.modelCount>=3&&f.consistency>=55&&quality>=40&&lead>=6&&reliability>=30){tier='B';reason='具备多模型和市场验证，但未达到A级完整要求'}else if(samples<3)reason=`历史样本不足（${samples}场）`;else if(f.modelCount<3)reason=`有效模型不足（${f.modelCount}个）`;else if(f.consistency<55)reason=`模型一致性不足（${f.consistency.toFixed(0)}%）`;else if(!official)reason='缺少完整体彩SP';return{version:'V16-P11',tier,reason,sampleCount:samples,reliability,quality:Math.round(quality),lead:Number(lead.toFixed(1)),modelCount:f.modelCount,consistency:f.consistency,officialSp:official}}
function enrich(m){const f=buildFusion(m),g=grade(m,f);return{...m,homeWinProb:f.probabilities[0],drawProb:f.probabilities[1],awayWinProb:f.probabilities[2],spf:{...(m.spf||{}),homeWinProb:f.probabilities[0],drawProb:f.probabilities[1],awayWinProb:f.probabilities[2],tier:g.tier},score:{...(m.score||{}),topScores:f.scores},modelFusion:f,calibratedTier:g.tier,grading:g}}
export async function onRequestGet(context){const u=new URL(context.request.url),q=new URLSearchParams();for(const [k,v] of u.searchParams)if(k!=='x')q.set(k,v);if(!q.has('days'))q.set('days','4');try{const r=await fetch(`${UPSTREAM}?${q}`,{headers:{accept:'application/json','user-agent':'Mozilla/5.0'}}),text=await r.text(),payload=JSON.parse(text);if(!r.ok||payload.success===false)return json({success:false,error:payload.error||`upstream ${r.status}`,matches:[]},502);const matches=(Array.isArray(payload.matches)?payload.matches:[]).map(enrich),gradeCounts=matches.reduce((a,m)=>(a[m.calibratedTier]++,a),{A:0,B:0,C:0});return json({...payload,success:true,total:matches.length,matches,gradeCounts,modelVersion:'V16-P11 Production Fusion',strategyAudit:{elo:'active-when-upstream-elo-exists',gxPoisson:'active-when-lambda-exists',dixonColes:'active-when-lambda-exists',legacy:'active-when-legacy-probability-exists',sportteryMarket:'active-when-three-sp-exist',multiCompanyOdds:'not-available-no-source',asianHandicapMovement:'not-available-no-source',injuriesLineups:'not-available-no-source',weather:'not-available-no-source',marketHeat:'not-available-no-real-flow-source',calibration:'collecting-full-review-samples',dynamicWeights:'disabled-until-sufficient-sample'}})}catch(e){return json({success:false,error:e.message,matches:[]},502)}}